esphome:
  name: floor-heating-controller-s2
  comment: Floor Heating Controller with sensorless BDC Motor valve actuators

  platformio_options:
    upload_speed: 115200
    
  project:
    name: "floor_heating_controller.s2"
    version: "0.0.1"

esp32:
  board: lolin_s2_mini
  framework:
    type: esp-idf
    version: 5.1.1
    platform_version: 6.4.0

web_server:
  local: true

logger:
  level: VERBOSE
  baud_rate: 115200
  deassert_rts_dtr: true
  hardware_uart: USB_CDC

debug:
  update_interval: 5s

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s


# It is highly recommended to use secrets
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "FHCS2 Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

status_led:
  pin: 15    

external_components:
# use all components from a local folder
  - source:
      type: local
      path: ./custom_components


valve:
  id: test_valve